### ISSUE TITLE
Plugin coverage not recorded on Gradle 8.7

### ISSUE THREAD

**Issue by ogolberg** [open-toast/testkit-plugins#7]
Likely due to https://github.com/gradle/gradle/issues/27328. In testkit tests, plugin classes are now transformed via the Gradle agent, which prevents them from being further transformed by the jacoco agent.

See `canRetransform` in https://docs.oracle.com/javase/8/docs/api/java/lang/instrument/Instrumentation.html#addTransformer-java.lang.instrument.ClassFileTransformer-boolean-

**Comment by asodja** [comment]
FYI: I believe https://github.com/gradle/gradle/pull/28730 that is planned for 8.8 should revert the behaviour. See also https://github.com/gradle/gradle/issues/28729.

**Comment by ogolberg** [comment]
fixed in https://github.com/open-toast/testkit-plugins/pull/10 using pre-instrumentation
